### ISSUE TITLE
خطأ إملائي بسيط في مقال JWT

### ISSUE THREAD

**Issue by MuhammadRabi** [Eqraatech/Software-Engineering-In-Arabic#1]
يوجد خطأ إملائي بسيط كما هو موضح ف الصورة المرفقة

يُرجى التغيير إلى "الجزء الثالث" و "التبعية"

جزاكم الله خير على مجهودكم الرائع

![Eqraa-issue](https://github.com/Eqraatech/Software-Engineering-In-Arabic/assets/34184092/b44eb10c-382d-4f01-96b4-4155dad3a2e0)

**Comment by mahyoussef** [comment]
شكرًأ جدا ليك يا محمد وآسف جدًا على التأخير عشان كنا في رمضان وكده , حقيقي متشكر ليك جدًا 😍
